"""Add token tracking columns to conversations

Revision ID: 1bc4b448f16c
Revises: f55f33ef573e
Create Date: 2026-04-25 20:41:20.550172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '1bc4b448f16c'
down_revision: Union[str, Sequence[str], None] = 'f55f33ef573e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('prompt_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('conversations', sa.Column('completion_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    op.add_column('conversations', sa.Column('total_tokens', sa.BigInteger(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'total_tokens')
    op.drop_column('conversations', 'completion_tokens')
    op.drop_column('conversations', 'prompt_tokens')
    # ### end Alembic commands ###
