"""add conversation pins

Revision ID: 2026c7ed4c8d
Revises: d66899aad3c9
Create Date: 2026-09-30 13:39:43.759836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '2026c7ed4c8d'
down_revision: Union[str, Sequence[str], None] = 'd66899aad3c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'is_pinned')
    # ### end Alembic commands ###
