"""add_image_url_to_messages

Revision ID: 4d61b08a5e0e
Revises: 1bc4b448f16c
Create Date: 2026-09-29 19:48:14.528220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '4d61b08a5e0e'
down_revision: Union[str, Sequence[str], None] = '1bc4b448f16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###
