"""Add summary column to conversations table for sliding window summarization

Revision ID: 87d83e2c6cf9
Revises: af5f1f478440
Create Date: 2026-04-25 19:43:52.187500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = '87d83e2c6cf9'
down_revision: Union[str, Sequence[str], None] = 'af5f1f478440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary')
    # ### end Alembic commands ###
