"""add role/user or assistant column at the message table

Revision ID: af5f1f478440
Revises: 730551788fa6
Create Date: 2026-04-24 21:49:28.340604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'af5f1f478440'
down_revision: Union[str, Sequence[str], None] = '730551788fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Clear old JSONB interaction data; row-per-message redesign makes it obsolete
    op.execute("TRUNCATE TABLE messages RESTART IDENTITY CASCADE")
    op.add_column('messages', sa.Column('role', sa.VARCHAR(), nullable=False))
    op.alter_column('messages', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###
