"""change column in users, add verified col

Revision ID: ba3201e0c657
Revises: bd8d41c316db
Create Date: 2026-04-15 18:07:10.645950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'ba3201e0c657'
down_revision: Union[str, Sequence[str], None] = 'bd8d41c316db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_msg_metadata_id'), 'msg_metadata', ['id'], unique=False)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('users', 'is_verified')
    op.drop_index(op.f('ix_msg_metadata_id'), table_name='msg_metadata')
    # ### end Alembic commands ###
