"""Change content col in messages to JSONB type

Revision ID: bcaf644c9cf7
Revises: 58f4ddf238a5
Create Date: 2026-04-15 19:06:36.861950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bcaf644c9cf7'
down_revision: Union[str, Sequence[str], None] = '58f4ddf238a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.VARCHAR(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               postgresql_using='content::jsonb')
    op.drop_column('messages', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('role', postgresql.ENUM('user', 'assistant', 'system', name='message_role'), autoincrement=False, nullable=True))
    op.alter_column('messages', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
