"""init_fresh

Revision ID: bd8d41c316db
Revises: 
Create Date: 2026-04-14 22:13:32.439503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 


# revision identifiers, used by Alembic.
revision: str = 'bd8d41c316db'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop and recreate msg_metadata table to change message_id from UUID to INTEGER
    op.drop_table('msg_metadata')
    op.create_table('msg_metadata',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('message_id', sa.INTEGER(), nullable=False),
        sa.Column('model_name', sa.VARCHAR(), nullable=False),
        sa.Column('tokens_used', sa.INTEGER(), nullable=False),
        sa.Column('response_time_ms', sa.DOUBLE_PRECISION(), nullable=False),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'msg_metadata', type_='foreignkey')
    op.create_unique_constraint(op.f('msg_metadata_message_id_key'), 'msg_metadata', ['message_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('msg_metadata', 'message_id',
               existing_type=sa.INTEGER(),
               type_=sa.UUID(),
               existing_nullable=False)
    # ### end Alembic commands ###
