"""add image_urls to messages

Revision ID: d66899aad3c9
Revises: 4d61b08a5e0e
Create Date: 2026-09-29 20:07:54.208953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel 
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd66899aad3c9'
down_revision: Union[str, Sequence[str], None] = '4d61b08a5e0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_urls', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('messages', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('messages', 'image_urls')
    # ### end Alembic commands ###
